baseURL = 'https://hobodiscgolf.com'
title = "Hobo Disc Golf:  Going NoMad"
languageCode = "en-us"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

#enableInlineShortcodes = true
#enableRobotsTXT = true

# Disqus Comment System
#disqusShortname = ""

[params]
# set below parameter to define a favicon
# favicon = "favicon.ico"

# set to change date format
  dateFormat = "2023.09.21"

# backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
#  [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"
