name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkoput@v2 
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2 
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2 
        with:
          github_token: ${{ secrets.mytoken }}
          publish_dir: ./public
